name: Repair & Build Flutter Android

on:
  workflow_dispatch: {}   # du kör den manuellt i Actions

permissions:
  contents: write         # krävs för att committa tillbaka

jobs:
  repair_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'   # använd samma som du har lokalt

      - name: Pub get
        run: flutter pub get

      # ⚡ Läs projektets namn från pubspec.yaml
      - name: Extract project name
        id: project_name
        run: |
          NAME=$(grep '^name:' pubspec.yaml | awk '{print $2}')
          echo "project_name=$NAME" >> $GITHUB_OUTPUT

      # ⚡ Återskapa android-mappen med rätt namn
      - name: Regenerate Android platform
        run: flutter create --platforms=android .
        env:
          FLUTTER_PROJECT_NAME: ${{ steps.project_name.outputs.project_name }}

      # Säkerställ Gradle 8.x om den inte är uppdaterad
      - name: Force Gradle 8.x
        run: |
          FILE=android/gradle/wrapper/gradle-wrapper.properties
          if [ -f "$FILE" ]; then
            sed -i 's/gradle-[0-9]\+\(\.[0-9]\+\)\?-all.zip/gradle-8.2-all.zip/g' "$FILE" || true
          fi

      # Commit:a tillbaka Android-filerna
      - name: Commit regenerated Android files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: repair android platform (auto)" || echo "No changes to commit"
          git push

      # Bygg APK
      - name: Build APK
        run: flutter build apk --release

      # Ladda upp APK som artefakt
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/apk/release/*.apk